In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Department": ["HR", "HR", "IT", "IT", "Marketing", "Marketing", "Sales", "Sales"],
    "Team": ["A", "A", "B", "B", "C", "C", "D", "D"],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Salary": [85, 90, 78, 85, 92, 88, 75, 80],
    "Age": [23, 25, 30, 22, 28, 26, 21, 27],
    "JoinDate": pd.to_datetime([
        "2020-01-10", "2020-02-15", "2021-03-20", "2021-04-10",
         "2020-05-30", "2020-06-25", "2021-07-15", "2021-08-01"
    ])
})  

# df = pd.DataFrame({
#     "Department" :["HR", "HR", "IT", "IT", "Marketing", "Marketing", "Sales", "Sales",

In [3]:
df

  Department Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
2         IT    B      M      78   30 2021-03-20
3         IT    B      F      85   22 2021-04-10
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25
6      Sales    D      M      75   21 2021-07-15
7      Sales    D      F      80   27 2021-08-01

In [4]:
# df.groupby("Department")["Salary"].mean()
df.groupby("Department")["Salary"].mean()

Department
HR           87.5
IT           81.5
Marketing    90.0
Sales        77.5
Name: Salary, dtype: float64

In [5]:
# df.groupby("Team")["Salary"].sum() # Average per team
df.groupby("Department")["Salary"].sum()

Department
HR           175
IT           163
Marketing    180
Sales        155
Name: Salary, dtype: int64

In [6]:
# df.groupby("Team")["Salary"].count()    # How many entries
df.groupby("Department")["Salary"].count()

Department
HR           2
IT           2
Marketing    2
Sales        2
Name: Salary, dtype: int64

In [7]:
# df.groupby("Team")["Salary"].min()
df.groupby("Department")["Salary"].min()

Department
HR           85
IT           78
Marketing    88
Sales        75
Name: Salary, dtype: int64

In [8]:
# df.groupby("Team")["Salary"].max()
df.groupby("Department")["Salary"].max()

Department
HR           90
IT           85
Marketing    92
Sales        80
Name: Salary, dtype: int64

In [9]:
# df.groupby("Team")["Salary"].std()
df.groupby("Department")["Salary"].std()

Department
HR           3.535534
IT           4.949747
Marketing    2.828427
Sales        3.535534
Name: Salary, dtype: float64

In [10]:
# df.groupby("Team")["Salary"].agg(["mean", "max", "min"]).reset_index().rename_axis(None,axis=1)

df.groupby("Team")["Salary"].agg(["min","max","mean"]).reset_index().rename_axis(None,axis=1)

  Team  min  max  mean
0    A   85   90  87.5
1    B   78   85  81.5
2    C   88   92  90.0
3    D   75   80  77.5

In [17]:
type(df)

pandas.core.frame.DataFrame

In [29]:
# df.groupby("Team")["Salary"].aggregate(
#     avg_score="mean",
#     high_score="max"
# ).reset_index().rename_axis(None,axis=1)

df.groupby("Team")["Salary"].agg(avg_score="mean",high_score ="max").reset_index().rename_axis(None,axis = 1)

  Team  avg_score  high_score
0    A       87.5          90
1    B       81.5          85
2    C       90.0          92
3    D       77.5          80

In [11]:
df.groupby("Team")["Salary"].aggregate(avg_score ="mean",high_score = "max")

      avg_score  high_score
Team
A          87.5          90
B          81.5          85
C          90.0          92
D          77.5          80

In [12]:
# df["Team Avg"] = df.groupby("Team")["Salary"].transform("mean")
df["Team Avg"] = df.groupby("Team")["Salary"].transform("mean")

In [13]:
df

  Department Team Gender  Salary  Age   JoinDate  Team Avg
0         HR    A      M      85   23 2020-01-10      87.5
1         HR    A      F      90   25 2020-02-15      87.5
2         IT    B      M      78   30 2021-03-20      81.5
3         IT    B      F      85   22 2021-04-10      81.5
4  Marketing    C      M      92   28 2020-05-30      90.0
5  Marketing    C      F      88   26 2020-06-25      90.0
6      Sales    D      M      75   21 2021-07-15      77.5
7      Sales    D      F      80   27 2021-08-01      77.5

In [18]:
# df.groupby("Team").filter(lambda x: x["Salary"].mean() > 85)
df.groupby("Team").filter(lambda x : x["Salary"].mean()>88)

  Department Team Gender  Salary  Age   JoinDate  Team Avg
4  Marketing    C      M      92   28 2020-05-30      90.0
5  Marketing    C      F      88   26 2020-06-25      90.0

In [19]:
df

  Department Team Gender  Salary  Age   JoinDate  Team Avg
0         HR    A      M      85   23 2020-01-10      87.5
1         HR    A      F      90   25 2020-02-15      87.5
2         IT    B      M      78   30 2021-03-20      81.5
3         IT    B      F      85   22 2021-04-10      81.5
4  Marketing    C      M      92   28 2020-05-30      90.0
5  Marketing    C      F      88   26 2020-06-25      90.0
6      Sales    D      M      75   21 2021-07-15      77.5
7      Sales    D      F      80   27 2021-08-01      77.5