In [2]:
import pandas as pd

In [3]:
data = [["Aditya",20],["Sumit",21],["Sunil",56],["Nita",47]]

In [4]:
df = pd.DataFrame(data,columns = ["Name","Age"])

In [5]:
print(df)

     Name  Age
0  Aditya   20
1   Sumit   21
2   Sunil   56
3    Nita   47

In [6]:
data = { "a":[44,65,75],"b":[78,67,54]}

In [7]:
df = pd.DataFrame(data)

In [8]:
print(df)

    a   b
0  44  78
1  65  67
2  75  54

In [9]:
import numpy as np

In [10]:
arr = np.array([[1,2],[3,4]])

In [11]:
df = pd.DataFrame(arr,columns = ["A","B"])

In [12]:
print(df)

   A  B
0  1  2
1  3  4

In [13]:
df = pd.read_excel("data1.xlsx")
# pd.read_excel("Data.xlsx")

In [14]:
df

     Name  Age    Citya
0  Aditya   20   Nashik
1   Sumit   23   Nahsik
2    Nita   46  Khandwa
3   Sunil   56  khandwa

In [15]:
df = pd.read_csv("Data.csv")

In [16]:
df

     Name  Age
0  Aditya   20
1   Sumit   23
2   Sunil   56
3    Nita   46
4    John   54
5    Marc   65

In [17]:
df = pd.read_json("data.json")

In [18]:
df

     Name Language
0  Aditya    Python
1   Sumit      Dart

In [19]:
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")

In [22]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [24]:
df.head()         # First 5 rows

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [26]:
df.tail()         # Last 5 rows

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [27]:
df.info()         # Column info: types, non-nulls

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [28]:
df.describe()     # Stats for numeric columns

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [29]:
df.columns        # List of column names

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [30]:
df.shape          # (rows, columns)

(244, 7)