In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data1.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [4]:
# df.sort_values("Age")                   # Ascending sort
# df.sort_values("Age", ascending=False)  # Descending
# df.sort_values(["Age", "Salary"])       # Sort by multiple columns

In [5]:
df.sort_values("Year")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [6]:
df.sort_values("Year",ascending = False)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [7]:
df2 = df.sort_values(["Year","IMDb"]).copy()

In [8]:
# df2.reset_index(drop = True,inplace=True)

In [9]:
df2.sort_index()

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [10]:
#Give The Ranking 
# df2["Rank"] = df2["IMDb"].rank(ascending = False,method = "dense")
df2["Rank"] = df2["IMDb"].rank(ascending = False,method = "dense")

In [11]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
7,Hrithik Roshan,War,2019,Action,475,6.5,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0

In [37]:
#Renameing columns 
# df2.rename(columns={"Actor": "ACTOR"}, inplace=False)
# df.rename(index={0: "row1", 1: "row2"}, inplace=True)

# df2.rename(columns={"Actor": "Enterner"})
df.rename(index = {0:"Row1",1:"Row2",2:"Row3",3:"Row4",4:"Row4",5:"Row5",6:"Row6",7:"Row7",8:"Row8",9:"Row9",10:"Row10",11:"Row11"})

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
Row1,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
Row2,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
Row3,Aamir Khan,Dangal,2016,Biography,2024,8.4
Row4,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
Row4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
Row5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
Row6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
Row7,Hrithik Roshan,War,2019,Action,475,6.5
Row8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
Row9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
Row10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
Row11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [31]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
7,Hrithik Roshan,War,2019,Action,475,6.5,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0

In [78]:
#Renaming Columns
df2.columns = ["ACTOR","FILM", "YEAR","GENRE","BOXOFFICE(INR Crore)","imdb","RANK"]

In [79]:
df2

,ACTOR,FILM,YEAR,GENRE,BOXOFFICE(INR Crore),imdb,RANK
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
7,Hrithik Roshan,War,2019,Action,475,6.5,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0

In [ ]:
#Changing Column order
# df = df[["City", "Name", "Age"]]   # Reorder as desired

In [84]:
df2 = df2[["FILM","ACTOR","GENRE","YEAR","imdb","BOXOFFICE(INR Crore)"]]

In [85]:
df2

,FILM,ACTOR,GENRE,YEAR,imdb,BOXOFFICE(INR Crore)
2,Dangal,Aamir Khan,Biography,2016,8.4,2024
1,Tiger Zinda Hai,Salman Khan,Action,2017,6.0,565
10,Badrinath Ki Dulhania,Varun Dhawan,Romantic Comedy,2017,6.1,201
4,Padmaavat,Ranveer Singh,Historical,2018,7.0,585
6,Stree,Rajkummar Rao,Horror Comedy,2018,7.5,180
5,Andhadhun,Ayushmann Khurrana,Thriller,2018,8.3,111
7,War,Hrithik Roshan,Action,2019,6.5,475
8,Good Newwz,Akshay Kumar,Comedy,2019,7.0,318
11,Uri: The Surgical Strike,Vicky Kaushal,Action,2019,8.2,342
3,Brahmastra,Ranbir Kapoor,Fantasy,2022,5.6,431
9,Bhool Bhulaiyaa 2,Kartik Aaryan,Horror Comedy,2022,5.9,266
0,Pathaan,Shah Rukh Khan,Action,2023,7.2,1050

In [39]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2