In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("dataCleaning.csv")

In [5]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [5]:
#this statement is used to check null values
# df.isnull()              # True for NaNs
# df.isnull().sum()        # Count missing per column

In [6]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [7]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [9]:
#this statement is used to drop a specific row and column where the missing value is found
# df.dropna()              # Drop rows with *any* missing values
# df.dropna(axis=1)        # Drop columns with missing values

In [7]:
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com    1/5/2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12/11/2019
6  Alice  25.0     New York      F  alice@example.com    1/5/2021
7  Alice  25.0     New York      F  alice@example.com    1/5/2021

In [8]:
df.dropna(axis = 1)

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [13]:
# This command is used for filling missing data
# df.fillna(0)                     # Replace NaN with 0

#below command work same 
# df["Age"].fillna(df["Age"].mean())  # Replace with mean
# df.ffill()      # Forward fill
# df.bfill()      # Backward fill

In [14]:
df.fillna(0)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [6]:
# df["Age"].fillna(df["Age"].mean())  # Replace with mean
df["Age"].fillna(df["Age"].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [7]:
df.ffill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5    David  28.0        Delhi      F     eve@domain.com  12/11/2019
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [8]:
df.bfill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5    Alice  28.0        Delhi      F     eve@domain.com    1/5/2021
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [24]:
#this is valid but not in future version of pandas
# df.fillna(method="ffill")
# df.fillna(method = "bfill")

In [28]:
#This method is used for finding duplictaes and  droping duplicates
# df.duplicated()          # True for duplicates
# df.drop_duplicates()     # Remove duplicate rows

In [9]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [30]:
df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [31]:
#checking based on specific colunm
# df.duplicated(subset=["Name", "Age"])

In [32]:
df.duplicated(subset = ["Name","Age"])

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [33]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [35]:
#string Operations
# df["Name"].str.lower() # Converts all names to lowercase.
# df["City"].str.contains("delhi", case=False) # Checks if 'delhi' is in the city name, case-insensitive.
# df["Email"].str.split("@") # Outputs a pandas Series where each element is a list of strings (the split parts). This is where a Python list comes into play, but the outer object is still a pandas Series.

In [36]:
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [37]:
df["Name"].str.upper()

0      ALICE
1    CHARLIE
2        BOB
3    CHARLIE
4      DAVID
5        NaN
6      ALICE
7      ALICE
8    CHARLIE
Name: Name, dtype: object

In [10]:
df["City"].str.contains("delhi",case = False)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [45]:
df["Email"].str.split("@")

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [46]:
#Type Conversion
# df["Age"] = df["Age"].astype(int)
# df["Date"] = pd.to_datetime(df["Date"])
# df["Category"] = df["Category"].astype("category")

In [150]:
df2 = df.dropna().copy()

In [151]:
df2

    Name   Age         City  Gender              Email   Join Date
0  Alice  25.0     New York  Female  alice@example.com    1/5/2021
2    Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020
4  David  22.0       Mumbai    Male  david@example.com  12/11/2019
6  Alice  25.0     New York  Female  alice@example.com    1/5/2021
7  Alice  25.0     New York  Female  alice@example.com    1/5/2021

In [123]:
df2["Age"]= df2["Age"].astype(int)

In [124]:
df2

    Name  Age         City  Gender              Email   Join Date
0  Alice   25     New York  Female  alice@example.com    1/5/2021
2    Bob   30  Los Angeles    Male    bob@example.com  15-06-2020
4  David   22       Mumbai    Male  david@example.com  12/11/2019
6  Alice   25     New York  Female  alice@example.com    1/5/2021
7  Alice   25     New York  Female  alice@example.com    1/5/2021

In [87]:
#Using Lambda Function 
# df["Age Group"] = df["Age"].apply(lambda x: "Adult" if x >= 18 else "Minor")

In [131]:
#Applying Function ,use apply() keyword
# .apply() → Apply any function to rows or columns
#Using Normal function 
def isminor(x):
    if(x>=25):
        return "Adult"
    else:
        return "Minor"
df2["Age Group"] = df2["Age"].apply(isminor)

In [132]:
df2

    Name  Age         City Gender              Email   Join Date Age Group
0  Alice   25     New York    NaN  alice@example.com    1/5/2021     Adult
2    Bob   30  Los Angeles    NaN    bob@example.com  15-06-2020     Adult
4  David   22       Mumbai    NaN  david@example.com  12/11/2019     Minor
6  Alice   25     New York    NaN  alice@example.com    1/5/2021     Adult
7  Alice   25     New York    NaN  alice@example.com    1/5/2021     Adult

In [145]:
#Applying Map Function 
# .map() → Element-wise mapping for Series
gender_map = {"M": "Male", "F": "Female"}
df["Gender"] = df["Gender"].map(gender_map)

In [146]:
# gender_map = {"M":"Male","F":"Female","O":"Others"}
# df["Gender"] = df["Gender"].map(gender_map)

In [147]:
df

      Name   Age         City  Gender              Email   Join Date
0    Alice  25.0     New York  Female  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021
4    David  22.0       Mumbai    Male  david@example.com  12/11/2019
5      NaN  28.0        Delhi  Female     eve@domain.com         NaN
6    Alice  25.0     New York  Female  alice@example.com    1/5/2021
7    Alice  25.0     New York  Female  alice@example.com    1/5/2021
8  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021

In [152]:
df2

    Name   Age         City  Gender              Email   Join Date
0  Alice  25.0     New York  Female  alice@example.com    1/5/2021
2    Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020
4  David  22.0       Mumbai    Male  david@example.com  12/11/2019
6  Alice  25.0     New York  Female  alice@example.com    1/5/2021
7  Alice  25.0     New York  Female  alice@example.com    1/5/2021

In [155]:
gender_map = {"Male" : "M","Female":"F"}
df2["Gender"] = df2["Gender"].map(gender_map)

In [156]:
df2

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com    1/5/2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12/11/2019
6  Alice  25.0     New York      F  alice@example.com    1/5/2021
7  Alice  25.0     New York      F  alice@example.com    1/5/2021

In [160]:
df["City"].replace({"Delhi": "New Delhi", "Mumbai": "New Mumbai"})

0       New York
1      New Delhi
2    Los Angeles
3      New Delhi
4     New Mumbai
5      New Delhi
6       New York
7       New York
8      New Delhi
Name: City, dtype: object

In [161]:
df

      Name   Age         City  Gender              Email   Join Date
0    Alice  25.0     New York  Female  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021
4    David  22.0       Mumbai    Male  david@example.com  12/11/2019
5      NaN  28.0        Delhi  Female     eve@domain.com         NaN
6    Alice  25.0     New York  Female  alice@example.com    1/5/2021
7    Alice  25.0     New York  Female  alice@example.com    1/5/2021
8  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021

In [167]:
df2.dtypes

Name          object
Age          float64
City          object
Gender        object
Email         object
Join Date     object
dtype: object