In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data1.csv")

In [3]:
#Selecting Column Structure
# df["column_name"]        # Single column (as Series)
# df[["col1", "col2"]]     # Multiple columns (as DataFrame)

In [4]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [6]:
df['Actor']

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [11]:
df[["Actor","Year"]]

                 Actor  Year
0       Shah Rukh Khan  2023
1          Salman Khan  2017
2           Aamir Khan  2016
3        Ranbir Kapoor  2022
4        Ranveer Singh  2018
5   Ayushmann Khurrana  2018
6        Rajkummar Rao  2018
7       Hrithik Roshan  2019
8         Akshay Kumar  2019
9        Kartik Aaryan  2022
10        Varun Dhawan  2017
11       Vicky Kaushal  2019

In [12]:
#Selecting row by index
# df.loc[0]                # First row (by label)
# df.iloc[0]               # First row (by position)

In [13]:
df.loc[]

Actor                   Shah Rukh Khan
Film                           Pathaan
Year                              2023
Genre                           Action
BoxOffice(INR Crore)              1050
IMDb                               7.2
Name: 0, dtype: object

In [14]:
df.iloc[0]

Actor                   Shah Rukh Khan
Film                           Pathaan
Year                              2023
Genre                           Action
BoxOffice(INR Crore)              1050
IMDb                               7.2
Name: 0, dtype: object

In [16]:
#Select Specific Row and Column [cell]
# df.loc[0, "Name"]        # Value at row 0, column 'Name'
# df.iloc[0, 1]            # Value at row 0, column at index 1

In [23]:
df.loc[1,"IMDb"]

6.0

In [26]:
df.iloc[1,4]

565

In [28]:
#Sliceing 
# df.loc[0:2, ["Name", "Age"]]   # Rows 0 to 2, selected columns
# df.iloc[0:2, 0:2]              # Rows and cols by index position

In [35]:
df.loc[0:5,["Actor","Film","Year","Genre"]]

                Actor             Film  Year       Genre
0      Shah Rukh Khan          Pathaan  2023      Action
1         Salman Khan  Tiger Zinda Hai  2017      Action
2          Aamir Khan           Dangal  2016   Biography
3       Ranbir Kapoor       Brahmastra  2022     Fantasy
4       Ranveer Singh        Padmaavat  2018  Historical
5  Ayushmann Khurrana        Andhadhun  2018    Thriller

In [37]:
df.iloc[0:4,0:5]

            Actor             Film  Year      Genre  BoxOffice(INR Crore)
0  Shah Rukh Khan          Pathaan  2023     Action                  1050
1     Salman Khan  Tiger Zinda Hai  2017     Action                   565
2      Aamir Khan           Dangal  2016  Biography                  2024
3   Ranbir Kapoor       Brahmastra  2022    Fantasy                   431

In [38]:
#For Fast Accessing
# df.at[0, "Name"]       # Fast label-based access
# df.iat[0, 1]           # Fast position-based access

In [40]:
df.at[0,"Actor"]

'Shah Rukh Khan'

In [45]:
df.iat[3,1]

'Brahmastra'

In [5]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [17]:
df[(df['Year']>2018) &( df['IMDb']>6)]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [18]:
df.query('Year>2019 and IMDb>6')

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

In [28]:
IMDb  = 7.0
df.query("IMDb >@IMDb")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [29]:
df.query("6.0<IMDb <=8.2")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [55]:
df2 = df[['Actor','IMDb']].copy()

In [56]:
df2

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [57]:
df2.loc[0,'Actor'] = "Aditya Vaishnav"

In [58]:
df2

                 Actor  IMDb
0      Aditya Vaishnav   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [59]:
df2.iloc[1,0] = "Sumit"

In [60]:
df2

                 Actor  IMDb
0      Aditya Vaishnav   7.2
1                Sumit   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [77]:
df3 = df[['Actor','IMDb']].copy()

In [78]:
df3

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [83]:
df4 = df.iloc[0:3 , 0:3]

In [84]:
df4

            Actor             Film  Year
0  Shah Rukh Khan          Pathaan  2023
1     Salman Khan  Tiger Zinda Hai  2017
2      Aamir Khan           Dangal  2016

In [85]:
df5 = df.iloc[0:6,0:4].copy()

In [86]:
df5

                Actor             Film  Year       Genre
0      Shah Rukh Khan          Pathaan  2023      Action
1         Salman Khan  Tiger Zinda Hai  2017      Action
2          Aamir Khan           Dangal  2016   Biography
3       Ranbir Kapoor       Brahmastra  2022     Fantasy
4       Ranveer Singh        Padmaavat  2018  Historical
5  Ayushmann Khurrana        Andhadhun  2018    Thriller