In [2]:
# import pandas as pd 

# # Sample DataFrame
# data = {
#     'Name': ['Alice', 'Bob', 'Charlie'],
#     'Math': [85, 78, 92],
#     'Science': [90, 82, 89],
#     'English': [88, 85, 94]
# }

# df = pd.DataFrame(data)

# # Display the DataFrame
# print(df)

import pandas as pd
data = { 
    'Name':['Alice','Bob','Charlie'],
    'Math':[89,98,79],
    'Science':[65,83,73],
    'English':[78,90,53]
}
df = pd.DataFrame(data)

In [3]:
df

      Name  Math  Science  English
0    Alice    89       65       78
1      Bob    98       83       90
2  Charlie    79       73       53

In [4]:
#Using melt keyward
# df.melt(id_vars=None, value_vars=None, var_name=None, value_name="value", col_level=None)
# df2 = df.melt(id_vars="Name",value_vars=["Math","Science","English"],var_name="Subject",value_name="Score")
# df2 = df.melt(id_vars = "Name",value_vars=["Math","Science","English"],var_name = "Subject",value_name = "Score")
df2 = df.melt(id_vars = "Name",value_vars = ["Math","Science","English"],var_name = "Subject",value_name = "Marks")
df2 = df.melt(id_vars = "Name",value_vars = ["Math","Science","English"],var_name = "Subject",value_name = "Marlks")

In [5]:
df2

      Name  Subject  Marlks
0    Alice     Math      89
1      Bob     Math      98
2  Charlie     Math      79
3    Alice  Science      65
4      Bob  Science      83
5  Charlie  Science      73
6    Alice  English      78
7      Bob  English      90
8  Charlie  English      53

In [31]:
#pivot keyward
# df.pivot(index=None, columns=None, values=None)
df2.pivot(index="Name", columns="Subject", values="Marks").reset_index().rename_axis(None,axis=1)

      Name  English  Math  Science
0    Alice       78    89       65
1      Bob       90    98       83
2  Charlie       53    79       73