In [2]:
import pandas as pd

In [3]:

employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [4]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [5]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [7]:
# pd.merge(employees, departments, on="DeptID")

pd.merge(employees,departments,on = "DeptID")

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [8]:
# pd.merge(employees, departments, on="DeptID", how="left")
pd.merge(employees,departments,on = "DeptID",how = "left")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [9]:
# pd.merge(employees, departments, on="DeptID", how="right")
pd.merge(employees,departments,on = "DeptID",how = "right")

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [13]:
# pd.merge(employees, departments, on="DeptID", how="outer")

pd.merge(employees,departments,on = "DeptID",how = "outer")

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [15]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"]})

In [16]:
df1

    Name
0  Alice
1    Bob

In [17]:
df2

      Name
0  Charlie
1    David

In [18]:
pd.concat([df1, df2])

      Name
0    Alice
1      Bob
0  Charlie
1    David

In [19]:
pd.concat([df1,df2],axis = 1)

    Name     Name
0  Alice  Charlie
1    Bob    David

In [24]:
# df1 = pd.DataFrame({"ID": [1, 2]})
# df2 = pd.DataFrame({"Score": [90, 80]})

df1 = pd.DataFrame({"ID":[10,20,30]})
df2 = pd.DataFrame({"Score":[90,56,80]})

In [25]:
df1

   ID
0  10
1  20
2  30

In [26]:
df2

   Score
0     90
1     56
2     80

In [27]:
pd.concat([df1, df2], axis=1)

   ID  Score
0  10     90
1  20     56
2  30     80

In [19]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"],"Score":[356,768]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"],"Age":[65,76]})

In [20]:
df1

    Name  Score
0  Alice    356
1    Bob    768

In [21]:
df2

      Name  Age
0  Charlie   65
1    David   76

In [28]:

pd.concat([df1, df2], axis=1)

    Name  Score     Name  Age
0  Alice    356  Charlie   65
1    Bob    768    David   76