In [1]:
import pandas as pd

In [2]:
# df = pd.read_csv("data1.csv")
df = pd.read_csv("data1.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [4]:
# df=df[df["IMDb"]>6]
df = df[df["IMDb"]>6]

In [5]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [6]:
df.to_csv("data_Updated.csv",index = False)

In [50]:
data =[
{"ID" : 1 , "name" : "Aditya","Address":{"city" : "Khandwa","PinCode":"450001"}},
{"ID" : 2 , "name": "Sumit","Address":{"city" :"Nashik","PinCode":"452001"}}
    ]

In [51]:
data

[{'ID': 1,
  'name': 'Aditya',
  'Address': {'city': 'Khandwa', 'PinCode': '450001'}},
 {'ID': 2,
  'name': 'Sumit',
  'Address': {'city': 'Nashik', 'PinCode': '452001'}}]

In [52]:
df = pd.json_normalize(data)

In [53]:
df

   ID    name Address.city Address.PinCode
0   1  Aditya      Khandwa          450001
1   2   Sumit       Nashik          452001